---
ID: "cb4de31a-0baa-456d-8eda-c680b5a39c0f"
Parent: "82c03f8b-84a4-48fd-b5d4-e412555a37e3"
Template: "82c03f8b-84a4-48fd-b5d4-e412555a37e3"
Path: /sitecore/templates/Feature/Constellation/Page Tagging/Page Metadata/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1a61ece0-2b10-458c-81c7-1e080222da7b"
      Hint: browserTitle
      Value: $name
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20171121T152529Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\rcabral
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\rcabral
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "81b7f299-421b-40c4-bea5-90a81e9b8bf9"
    - ID: "aadca14b-9b41-4311-a4bc-7d8c395fcf19"
      Hint: inheritAuthorAndPublisher
      Value: 1
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\roberto.armas@verndale.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240626T233236Z
